### PR TITLE
Failed witness backoff

### LINKED ISSUE #128: Add exponential backoff to the Witness query
We frequently get timeout errors from them i.e. `witness.postLeafAndGetTimestamp failed for #1173302, "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8…", leafHash 0xd99489955e252fd7d2f83ec5ac2e039a04e62bf41e00f20a41a303079ac6e84f: Error: Timeout waiting for checkpoint covering leafIndex 31498519` so add exponential backoff and retry logic.

### PR DESCRIPTION
**Pull request by sukhman-sukh**
This PR adds exponential backoff for failed queries during witness generation, starting with a 1-second delay and doubling exponentially with each attempt. It also includes checks for maxRetries and maxDelay.

### CODE REVIEW

File: src/lib/generateWitness.ts [hunk 1]
```diff
@@ -3,32 +3,74 @@ import { getCanonicalRecordString } from "./utils";
...
+    `proof chain verified, setting provenanceVerified for ${recordToString(
+      dkimRecord
+    )}`
+  );
+  await prisma.dkimRecord.update({
+    where: {
+      id: dkimRecord.id,
+    },
+    data: {
+      provenanceVerified: true,
```
Comment (Divide-By-0) [inline src/lib/generateWitness.ts:73]: can we store the leafhash somewhere so we can access the witness commitment later?

Comment (Divide-By-0) [reply src/lib/generateWitness.ts:73]: jk we already do
